// @ts-nocheck
import { serve } from "https://deno.land/std@0.190.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');
const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

serve(async (req) => {
  // Handle CORS
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const supabase = createClient(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY!);
    
    // 1. Get request body
    const { action, tone, data } = await req.json();

    console.log(`[ai-coach] Request received: Action=${action}, Tone=${tone}`);

    if (!GEMINI_API_KEY) {
      throw new Error("GEMINI_API_KEY is not set in Edge Function secrets.");
    }

    // 2. Fetch the active prompt for this action/tone
    let { data: promptData, error: promptError } = await supabase
      .from('ai_prompts')
      .select('system_instruction, version')
      .eq('action', action)
      .eq('coach_tone', tone)
      .eq('is_active', true)
      .single();

    if (promptError || !promptData) {
      console.error(`[ai-coach] Prompt not found for ${action}/${tone}`);
      // Fallback prompt if database lookup fails
      promptData = { 
        system_instruction: "You are a fitness coach. Analyze the data and provide a recommendation in JSON.", 
        version: "fallback" 
      };
    }

    // 3. Construct the message for Gemini
    const systemInstruction = promptData.system_instruction;
    const userMessage = JSON.stringify(data);

    // 4. Call Gemini API
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: `${systemInstruction}\n\nUser Data:\n${userMessage}` }]
        }],
        generationConfig: {
          response_mime_type: "application/json"
        }
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API Error: ${errorText}`);
    }

    const aiResult = await response.json();
    const generatedText = aiResult.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      throw new Error("No content generated by AI");
    }

    // Parse JSON safely
    let parsedOutput;
    try {
      parsedOutput = JSON.parse(generatedText);
    } catch (e) {
      console.error("[ai-coach] JSON Parse Error", generatedText);
      throw new Error("AI returned invalid JSON");
    }

    // 5. Log the interaction to ai_logs (asynchronously, don't await blocking response)
    /* 
      We use auth.uid() from the JWT in the request header usually, 
      but for simplicity in this MVP context, we assume the client passed user_id or we skip it.
      Ideally, we parse the JWT here.
    */
    
    // Return the result
    return new Response(JSON.stringify(parsedOutput), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error: any) {
    console.error(`[ai-coach] Error: ${error.message}`);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
})