// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tpypdprmcodqyzrysvxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRweXBkcHJtY29kcXl6cnlzdnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NTYzNzUsImV4cCI6MjA4NTQzMjM3NX0.BmeJsXIlNvyHhrvaW43QZVSEVcUu_ROvtX73EmkZdBk";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);